REVIEW_REPLIES = [
    "Review responsibly. No dark side stuff.",
    "You were chosen by the almighty RNG. Blame the universe.",
    "The prophecy foretold of this review.",
    "You're the lucky winner(s) of today's review lottery!",
    "Don't worry, the bugs are afraid of you. Probably.",
    "The random number gods have spoken.",
    "You're the chosen one(s). There's no escape.",
    "Good luck. You'll need it (just kidding… maybe).",
    "I promise this isn't a punishment.",
    "This is the way.",
    "Remember, with great reviewing power comes great responsibility.",
    "Trust me, +10000 -9898 is not a big diff.",
    "If you don't review, I'll assign you again tomorrow.",
    "The bot has spoken. Resistance is futile.",
    "Don't make me assign the cat. She only types 'meow'.",
    "You've been volunteered! Congratulations.",
    "Telemetry shows you are online. Resistance is futile.",
    "The tumbling space potato of fate has landed on you.",
     "A merge request without a reviewer is like a satellite without a ground station.",
]

MR_NOT_FOUND_REPLIES = [
    "Merge request does not exist. Review your manners instead.",
    "404: Merge request not found.",
    "This MR is a myth, a legend, a pull request that never was.",
    "No MR here. Maybe it went on a long vacation with the missing semicolons.",
    "MR not found. Are you sure you didn't dream it?",
    "Invalid MR link. The only thing to review is your copy-paste skills.",
    "That merge request has left the repository. It's in a better place now.",
    "Zero MRs found. Time to review your life choices.",
    "This MR doesn't exist. But you know what does? Regret.",
    "No merge request. Maybe it was just a merge suggestion whispered into the void.",
    "MR not found. If it was a feature, it's a very hidden one.",
    "I can't assign reviewers to nothing. Even I have standards.",
]

NOBODY_ELIGIBLE_REPLIES = [
    "Nobody eligible to pick. People you pinged are on vacation.",
    "The review pool is empty. Everyone has escaped to a parallel dimension.",
    "Eligible reviewers: 0. Apparently, it's a universal holiday.",
    "No one available. Give it a try in a few years.",
    "The only eligible reviewer is a tumbleweed. It doesn't know code.",
    "The RNG gods are crying - no sacrifices to choose from.",
    "Eligible reviewers: none. Requested reviewers retired to a farm.",
    "No one to review. Maybe the code can review itself?",
    "The random selector returned: 'nobody'. So here we are.",
    "Eligible: nobody. The review session is cancelled due to lack of interest.",
    "No one qualifies. Perhaps you should review it yourself?",
]
